version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-sfn-processor"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ewtozaejq4ef"
s3_prefix = "sam-sfn-processor"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
